/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.petssystem.gui;

import com.mycompany.petssystem.entities.Pet;
import com.mycompany.petssystem.entities.TypePet;
import com.mycompany.petssystem.repository.PetRepository;
import com.mycompany.petssystem.repository.TypePetRepository;
import javax.swing.JOptionPane;

/**
 *
 * @author erick
 */
public class ConsultPet extends javax.swing.JInternalFrame {
    
    private final PetRepository petRepository = new PetRepository();
    private final TypePetRepository typePetRepository = new TypePetRepository();

    /**
     * Creates new form SearchPet
     */
    public ConsultPet() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelIDPet = new javax.swing.JLabel();
        txtConsultPet = new javax.swing.JTextField();
        jButtonConsultPet = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);

        labelIDPet.setFont(new java.awt.Font("Georgia", 3, 36)); // NOI18N
        labelIDPet.setText("ID");

        txtConsultPet.setFont(new java.awt.Font("Berlin Sans FB Demi", 2, 18)); // NOI18N
        txtConsultPet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsultPetActionPerformed(evt);
            }
        });

        jButtonConsultPet.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        jButtonConsultPet.setText("Buscar");
        jButtonConsultPet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultPetActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        jLabel1.setText("Buscar mascota");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(labelIDPet, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtConsultPet, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(jButtonConsultPet, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(147, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(184, 184, 184))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIDPet, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtConsultPet, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addComponent(jButtonConsultPet, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtConsultPetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsultPetActionPerformed
        
    }//GEN-LAST:event_txtConsultPetActionPerformed

    private void jButtonConsultPetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultPetActionPerformed
        try {
            int id = Integer.parseInt(txtConsultPet.getText());
            Pet pet = new Pet();
            pet.setId(id);
            Pet resultado = petRepository.getPet(pet);
            
           

            if (resultado != null) {
                TypePet typePet = new TypePet();
                typePet.setTypeId(resultado.getTypeId());
                TypePet tipo = typePetRepository.getTypePet(typePet);
                JOptionPane.showMessageDialog(null, "Nombre: " + resultado.getName() + "\n" +"Edad: " + resultado.getAge() + "\n" + "Tipo de mascota: " +tipo.getDescription() +"(" +
                    resultado.getTypeId()+")");
            } else {
            JOptionPane.showMessageDialog(null, "No se encontró ninguna mascota");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El ID debe ser un número");
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error: "+ e.getMessage());
        }
    }//GEN-LAST:event_jButtonConsultPetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConsultPet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelIDPet;
    private javax.swing.JTextField txtConsultPet;
    // End of variables declaration//GEN-END:variables
}
