/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.petssystem.gui;

import com.mycompany.petssystem.entities.TypePet;
import com.mycompany.petssystem.repository.TypePetRepository;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;

/**
 *
 * @author erick
 */
public class ConsultTypePet extends javax.swing.JInternalFrame {
    
    private TypePetRepository typePetRepository = new TypePetRepository();

    /**
     * Creates new form SearchTypePet
     */
    public ConsultTypePet() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabelConsultTypeID = new javax.swing.JLabel();
        txtConsultTypeId = new javax.swing.JTextField();
        jButtonConsultType = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setClosable(true);

        jLabelConsultTypeID.setFont(new java.awt.Font("Georgia", 3, 36)); // NOI18N
        jLabelConsultTypeID.setText("ID");

        txtConsultTypeId.setFont(new java.awt.Font("Berlin Sans FB Demi", 2, 18)); // NOI18N
        txtConsultTypeId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsultTypeIdActionPerformed(evt);
            }
        });

        jButtonConsultType.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        jButtonConsultType.setText("Buscar");
        jButtonConsultType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultTypeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        jLabel1.setText("Buscar tipo de mascota");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jLabelConsultTypeID)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonConsultType, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtConsultTypeId, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(152, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(124, 124, 124))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelConsultTypeID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtConsultTypeId))
                .addGap(53, 53, 53)
                .addComponent(jButtonConsultType, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConsultTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultTypeActionPerformed
        // TODO add your handling code here:
        try {
            
            int typeId = Integer.parseInt(txtConsultTypeId.getText());
            
            TypePet typePet = new TypePet();
            
            typePet.setTypeId(typeId);
            
            TypePet resultado = typePetRepository.getTypePet(typePet);
            
            if(resultado !=null){
                JOptionPane.showMessageDialog(null, "Descripcion: "+resultado.getDescription()+"\nID: "+resultado.getTypeId());
                txtConsultTypeId.setText("");
            }else{
                JOptionPane.showMessageDialog(null, "No se pudo consultar la mascota");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El ID debe se un numero entero");
        }
    }//GEN-LAST:event_jButtonConsultTypeActionPerformed

    private void txtConsultTypeIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsultTypeIdActionPerformed
        // TODO add your handling code here:
        
        
                
    }//GEN-LAST:event_txtConsultTypeIdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConsultType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelConsultTypeID;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txtConsultTypeId;
    // End of variables declaration//GEN-END:variables
}
