/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.petssystem.gui;

import com.mycompany.petssystem.entities.Pet;
import com.mycompany.petssystem.repository.PetRepository;
import javax.swing.JOptionPane;

/**
 *
 * @author erick
 */
public class DeletePet extends javax.swing.JInternalFrame {
    
    private final PetRepository petRepository = new PetRepository();

    /**
     * Creates new form DeletePet
     */
    public DeletePet() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelDeleteIDPet = new javax.swing.JLabel();
        txtDeleteIDPet = new javax.swing.JTextField();
        jButtonDeletePet = new javax.swing.JButton();

        setClosable(true);

        jLabelDeleteIDPet.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabelDeleteIDPet.setText("ID");

        txtDeleteIDPet.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtDeleteIDPet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeleteIDPetActionPerformed(evt);
            }
        });

        jButtonDeletePet.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jButtonDeletePet.setText("Borrar Mascota");
        jButtonDeletePet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletePetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jLabelDeleteIDPet)
                .addGap(35, 35, 35)
                .addComponent(txtDeleteIDPet, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonDeletePet)
                .addGap(96, 96, 96))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDeleteIDPet)
                    .addComponent(txtDeleteIDPet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(jButtonDeletePet)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDeleteIDPetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeleteIDPetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeleteIDPetActionPerformed

    private void jButtonDeletePetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletePetActionPerformed
        // TODO add your handling code here:
        
        try {
            int id = Integer.parseInt(txtDeleteIDPet.getText());
            int confirm = JOptionPane.showConfirmDialog(null, "¿Desea eliminar la mascota?");
            
            if(confirm==0){
                byte newStatus = 0;
            
                Pet pet = new Pet();
                pet.setId(id);
                pet.setStatus(newStatus);
                boolean result = petRepository.deletePet(pet);
            
                if(result){
                    JOptionPane.showMessageDialog(null, "La mascota fue eliminada");
                    txtDeleteIDPet.setText("");
                }else{
                    JOptionPane.showMessageDialog(null, "La mascota no fue eliminada");
                }
             
            }
            

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El ID debe ser un numero");
        }
    }//GEN-LAST:event_jButtonDeletePetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDeletePet;
    private javax.swing.JLabel jLabelDeleteIDPet;
    private javax.swing.JTextField txtDeleteIDPet;
    // End of variables declaration//GEN-END:variables
}
