/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.petssystem.gui;

import com.mycompany.petssystem.repository.PetRepository;
import com.mycompany.petssystem.repository.TypePetRepository;

/**
 *
 * @author erick
 */
public class Desktop extends javax.swing.JFrame {
    
    
    //Variables pa que no se abran otros formularios
    //pet
    private RegisterPet registerPet;
    private DeletePet deletePet;
    private ConsultPet consultPet;
    private UpdatePet updatePet;
    private TablePet tablePet;
    
    //typePet
    
    private RegisterTypePet registerTypePet;
    private DeleteTypePet deleteTypePet;
    private ConsultTypePet consultTypePet;
    private UpdateTypePet updateTypePet;
    private TableTypePet tableTypePet;
    
    private final PetRepository petRepository = new PetRepository();
    private final TypePetRepository typePetRepository = new TypePetRepository();

    /**
     * Creates new form Desktop
     */
    public Desktop() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        desktopFirst = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuItemRegistrarPet = new javax.swing.JMenuItem();
        menuItemSeePets = new javax.swing.JMenuItem();
        menuItemUpdatePet = new javax.swing.JMenuItem();
        menuItemDeletePet = new javax.swing.JMenuItem();
        menuItemVerTodo = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuItemRegisterTypePet = new javax.swing.JMenuItem();
        menuItemSeeTypePet = new javax.swing.JMenuItem();
        menuItemUpdateTypePet = new javax.swing.JMenuItem();
        menuItemDeleteTypePet = new javax.swing.JMenuItem();
        jMenuItemVerTodoType = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 102));

        desktopFirst.setBorder(javax.swing.BorderFactory.createEmptyBorder(100, 100, 100, 100));

        javax.swing.GroupLayout desktopFirstLayout = new javax.swing.GroupLayout(desktopFirst);
        desktopFirst.setLayout(desktopFirstLayout);
        desktopFirstLayout.setHorizontalGroup(
            desktopFirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 694, Short.MAX_VALUE)
        );
        desktopFirstLayout.setVerticalGroup(
            desktopFirstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 293, Short.MAX_VALUE)
        );

        getContentPane().add(desktopFirst, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Pet");
        jMenu1.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N

        menuItemRegistrarPet.setText("Registrar Mascota");
        menuItemRegistrarPet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRegistrarPetActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemRegistrarPet);

        menuItemSeePets.setText("Buscar Mascota");
        menuItemSeePets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSeePetsActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemSeePets);

        menuItemUpdatePet.setText("Actualizar datos");
        menuItemUpdatePet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemUpdatePetActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemUpdatePet);

        menuItemDeletePet.setText("Eliminar Mascota");
        menuItemDeletePet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemDeletePetActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemDeletePet);

        menuItemVerTodo.setText("Ver todas las mascotas");
        menuItemVerTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemVerTodoActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemVerTodo);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Type Pet");
        jMenu2.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N

        menuItemRegisterTypePet.setText("Registrar Tipo de mascota ");
        menuItemRegisterTypePet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRegisterTypePetActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemRegisterTypePet);

        menuItemSeeTypePet.setText("Buscar Tipo de mascota");
        menuItemSeeTypePet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSeeTypePetActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemSeeTypePet);

        menuItemUpdateTypePet.setText("Actualizar tipo de mascota");
        menuItemUpdateTypePet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemUpdateTypePetActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemUpdateTypePet);

        menuItemDeleteTypePet.setText("Eliminar Tipo de mascota");
        menuItemDeleteTypePet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemDeleteTypePetActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemDeleteTypePet);

        jMenuItemVerTodoType.setText("Ver todos los tipos de mascota");
        jMenuItemVerTodoType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVerTodoTypeActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemVerTodoType);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemRegistrarPetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRegistrarPetActionPerformed
        if (registerPet == null || registerPet.isClosed()) {
            registerPet = new RegisterPet();
            desktopFirst.add(registerPet);
        }
        registerPet.setVisible(true);
        

    }//GEN-LAST:event_menuItemRegistrarPetActionPerformed

    private void menuItemSeePetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSeePetsActionPerformed
        if(consultPet == null||consultPet.isClosed()){
            consultPet = new ConsultPet();
            desktopFirst.add(consultPet);
        }
        consultPet.setVisible(true);
                
    }//GEN-LAST:event_menuItemSeePetsActionPerformed

    private void menuItemRegisterTypePetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRegisterTypePetActionPerformed
        if(registerTypePet == null|| registerTypePet.isClosed()){
            registerTypePet = new RegisterTypePet();
            desktopFirst.add(registerTypePet);
        }
        registerTypePet.setVisible(true);
    }//GEN-LAST:event_menuItemRegisterTypePetActionPerformed

    private void menuItemUpdateTypePetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemUpdateTypePetActionPerformed
        if(updateTypePet == null|| updateTypePet.isClosed()){
            updateTypePet = new UpdateTypePet();
            desktopFirst.add(updateTypePet);
        }
        updateTypePet.setVisible(true);
    }//GEN-LAST:event_menuItemUpdateTypePetActionPerformed

    private void menuItemUpdatePetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemUpdatePetActionPerformed
        if(updatePet == null||updatePet.isClosed()){
            updatePet = new UpdatePet();
            desktopFirst.add(updatePet);
        }
        updatePet.setVisible(true);
    }//GEN-LAST:event_menuItemUpdatePetActionPerformed

    private void menuItemDeletePetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemDeletePetActionPerformed
        if(deletePet == null||deletePet.isClosed()){
            deletePet = new DeletePet();
            desktopFirst.add(deletePet);
        }
        deletePet.setVisible(true);
    }//GEN-LAST:event_menuItemDeletePetActionPerformed

    private void menuItemSeeTypePetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSeeTypePetActionPerformed
        if(consultTypePet == null|| consultTypePet.isClosed()){
            consultTypePet = new ConsultTypePet();
            desktopFirst.add(consultTypePet);
        }
        consultTypePet.setVisible(true);
    }//GEN-LAST:event_menuItemSeeTypePetActionPerformed

    private void menuItemDeleteTypePetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemDeleteTypePetActionPerformed
        if(deleteTypePet == null|| deleteTypePet.isClosed()){
            deleteTypePet = new DeleteTypePet();
            desktopFirst.add(deleteTypePet);
        }
        deleteTypePet.setVisible(true);
    }//GEN-LAST:event_menuItemDeleteTypePetActionPerformed

    private void menuItemVerTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemVerTodoActionPerformed
        if(tablePet == null || tablePet.isClosed()){
            tablePet = new TablePet();
            desktopFirst.add(tablePet);
        }
        tablePet.setVisible(true);
    }//GEN-LAST:event_menuItemVerTodoActionPerformed

    private void jMenuItemVerTodoTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVerTodoTypeActionPerformed
        if(tableTypePet == null || tableTypePet.isClosed()){
            tableTypePet = new TableTypePet();
            desktopFirst.add(tableTypePet);
        }
        tableTypePet.setVisible(true);
    }//GEN-LAST:event_jMenuItemVerTodoTypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Desktop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopFirst;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemVerTodoType;
    private javax.swing.JMenuItem menuItemDeletePet;
    private javax.swing.JMenuItem menuItemDeleteTypePet;
    private javax.swing.JMenuItem menuItemRegisterTypePet;
    private javax.swing.JMenuItem menuItemRegistrarPet;
    private javax.swing.JMenuItem menuItemSeePets;
    private javax.swing.JMenuItem menuItemSeeTypePet;
    private javax.swing.JMenuItem menuItemUpdatePet;
    private javax.swing.JMenuItem menuItemUpdateTypePet;
    private javax.swing.JMenuItem menuItemVerTodo;
    // End of variables declaration//GEN-END:variables
}
