/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.petssystem.gui;

import com.mycompany.petssystem.entities.TypePet;
import com.mycompany.petssystem.repository.TypePetRepository;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author erick
 */
public class RegisterTypePet extends javax.swing.JInternalFrame {
    
    private final TypePetRepository typePetRepository = new TypePetRepository();

    /**
     * Creates new form RegisterTypePet
     */
    public RegisterTypePet() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTipoTypeR = new javax.swing.JLabel();
        txtTipoTypeR = new javax.swing.JTextField();
        jButtonTypeR = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);

        jLabelTipoTypeR.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        jLabelTipoTypeR.setText("Tipo de mascota:");

        txtTipoTypeR.setFont(new java.awt.Font("Berlin Sans FB Demi", 2, 18)); // NOI18N
        txtTipoTypeR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoTypeRActionPerformed(evt);
            }
        });

        jButtonTypeR.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        jButtonTypeR.setText("Registrar");
        jButtonTypeR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTypeRActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        jLabel1.setText("Registrar tipo de mascota");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabelTipoTypeR, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTipoTypeR, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonTypeR, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(215, 215, 215))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(127, 127, 127))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTipoTypeR, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTipoTypeR, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jButtonTypeR, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTipoTypeRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoTypeRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoTypeRActionPerformed

    private void jButtonTypeRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTypeRActionPerformed
        
        try {
            String description = txtTipoTypeR.getText();
            
            TypePet typePet = new TypePet(description,(byte)1);
            
            
            boolean result = typePetRepository.registerTypePet(typePet);
            
            if(result){
                JOptionPane.showMessageDialog(null, "Se ha registrado el tipo de mascota");
                txtTipoTypeR.setText("");
            }else{
                JOptionPane.showMessageDialog(null, "No se ha registrado el tipo de mascota");
                txtTipoTypeR.setText("");
            }
            
        } catch (RuntimeException e) {
            JOptionPane.showMessageDialog(null, "Error: "+e.getMessage());    
        }
    }//GEN-LAST:event_jButtonTypeRActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonTypeR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelTipoTypeR;
    private javax.swing.JTextField txtTipoTypeR;
    // End of variables declaration//GEN-END:variables
}
