/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.petssystem.gui;

import com.mycompany.petssystem.entities.TypePet;
import com.mycompany.petssystem.repository.TypePetRepository;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author erick
 */
public class RegisterTypePet extends javax.swing.JInternalFrame {
    
    private final TypePetRepository typePetRepository = new TypePetRepository();

    /**
     * Creates new form RegisterTypePet
     */
    public RegisterTypePet() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTipoTypeR = new javax.swing.JLabel();
        txtTipoTypeR = new javax.swing.JTextField();
        jButtonTypeR = new javax.swing.JButton();

        jLabelTipoTypeR.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabelTipoTypeR.setText("Tipo de mascota(descripcion)");

        txtTipoTypeR.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTipoTypeR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoTypeRActionPerformed(evt);
            }
        });

        jButtonTypeR.setText("Registrar");
        jButtonTypeR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTypeRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabelTipoTypeR, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTipoTypeR, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonTypeR, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(245, 245, 245))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTipoTypeR, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTipoTypeR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonTypeR, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTipoTypeRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoTypeRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoTypeRActionPerformed

    private void jButtonTypeRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTypeRActionPerformed
        
        try {
            String description = txtTipoTypeR.getText();
            
            TypePet typePet = new TypePet();
            
            typePet.setDescription(description);
            
            boolean result = typePetRepository.registerTypePet(typePet);
            
            if(result){
                JOptionPane.showMessageDialog(null, "Se ha registrado el tipo de mascota");
                txtTipoTypeR.setText("");
            }else{
                JOptionPane.showMessageDialog(null, "No se ha registrado el tipo de mascota");
                txtTipoTypeR.setText("");
            }
            
        } catch (RuntimeException e) {
            JOptionPane.showMessageDialog(null, "Error: "+e.getMessage());    
        }
    }//GEN-LAST:event_jButtonTypeRActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonTypeR;
    private javax.swing.JLabel jLabelTipoTypeR;
    private javax.swing.JTextField txtTipoTypeR;
    // End of variables declaration//GEN-END:variables
}
