/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.petssystem.gui;

import com.mycompany.petssystem.entities.Pet;
import com.mycompany.petssystem.entities.TypePet;
import com.mycompany.petssystem.repository.PetRepository;
import com.mycompany.petssystem.repository.TypePetRepository;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author erick
 */
public class RegisterPet extends javax.swing.JInternalFrame {
    
    private final PetRepository petRepository = new PetRepository();
    private final TypePetRepository typePetRepository = new TypePetRepository();


    /**
     * Creates new form RegisterPet
     */
    public RegisterPet() {
        initComponents();
        loadTypes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNombreR = new javax.swing.JLabel();
        jLabelEdadR = new javax.swing.JLabel();
        jLabelTypePetR = new javax.swing.JLabel();
        jTextFieldNombreR = new javax.swing.JTextField();
        jTextFieldEdadR = new javax.swing.JTextField();
        jButtonRegistrarPet = new javax.swing.JButton();
        jComboBoxTypeR = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(60, 63, 64));
        setClosable(true);

        jLabelNombreR.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabelNombreR.setText("Nombre");

        jLabelEdadR.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabelEdadR.setText("Edad");

        jLabelTypePetR.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabelTypePetR.setText("Tipo de mascota");

        jTextFieldNombreR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreRActionPerformed(evt);
            }
        });

        jButtonRegistrarPet.setText("Registrar");
        jButtonRegistrarPet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarPetActionPerformed(evt);
            }
        });

        jComboBoxTypeR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxTypeR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTypeRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(jButtonRegistrarPet, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabelTypePetR))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(jLabelEdadR))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(jLabelNombreR)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldNombreR, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldEdadR, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jComboBoxTypeR, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(234, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombreR)
                    .addComponent(jTextFieldNombreR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEdadR)
                    .addComponent(jTextFieldEdadR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTypePetR, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                    .addComponent(jComboBoxTypeR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jButtonRegistrarPet, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNombreRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreRActionPerformed

    private void jButtonRegistrarPetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarPetActionPerformed
        // TODO add your handling code here:
        try {
            String name = jTextFieldNombreR.getText();
            short age = Short.parseShort(jTextFieldEdadR.getText());
            int index = jComboBoxTypeR.getSelectedIndex();
            TypePet tipo = typePetRepository.getAllTypePets().get(index);
            int typeId = tipo.getTypeId();

            Pet pet = new Pet(name, age, (byte) 1, typeId);
            boolean registPet = petRepository.registerPet(pet);

            if (registPet) {
                JOptionPane.showMessageDialog(null, "Mascota registrada");
                jTextFieldNombreR.setText("");
                jTextFieldEdadR.setText("");
                jComboBoxTypeR.setSelectedIndex(0);
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo registrar la mascota");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Edad y Tipo ID deben ser números enteros");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_jButtonRegistrarPetActionPerformed

    private void jComboBoxTypeRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTypeRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTypeRActionPerformed
    private void loadTypes() {
        jComboBoxTypeR.removeAllItems();
        try {
            List<TypePet> types = typePetRepository.getAllTypePets();
            for (TypePet t : types) {
                jComboBoxTypeR.addItem(t.getDescription());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegistrarPet;
    private javax.swing.JComboBox<String> jComboBoxTypeR;
    private javax.swing.JLabel jLabelEdadR;
    private javax.swing.JLabel jLabelNombreR;
    private javax.swing.JLabel jLabelTypePetR;
    private javax.swing.JTextField jTextFieldEdadR;
    private javax.swing.JTextField jTextFieldNombreR;
    // End of variables declaration//GEN-END:variables
}
