/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.petssystem.gui;

import com.mycompany.petssystem.entities.Pet;
import com.mycompany.petssystem.entities.TypePet;
import com.mycompany.petssystem.repository.PetRepository;
import com.mycompany.petssystem.repository.TypePetRepository;
import javax.swing.JOptionPane;

/**
 *
 * @author erick
 */
public class TablePet extends javax.swing.JInternalFrame {
    
    private final PetRepository petRepository = new PetRepository();
    private final TypePetRepository typePetRepository = new TypePetRepository();

    /**
     * Creates new form TablePet
     */
    public TablePet() {
        initComponents();
        loadPets();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadPets(){
        String[] columnas = {"ID", "Nombre", "Edad", "Type"};
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(columnas, 0){
            @Override public boolean isCellEditable(int r,int c){return false;}
        };
        try {
            for(Pet p:petRepository.getAllPets()){
                TypePet typePet = new TypePet();
                typePet.setTypeId(p.getTypeId());
                TypePet tipo = typePetRepository.getTypePet(typePet);
                String descripcion = tipo.getDescription();
                model.addRow(new Object[]{p.getId(), p.getName(),p.getAge(), descripcion});
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: "+e.getMessage());
        }
        jTable1.setModel(model);
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
