/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.petssystem.gui;

import com.mycompany.petssystem.entities.Pet;
import com.mycompany.petssystem.entities.TypePet;
import com.mycompany.petssystem.repository.PetRepository;
import com.mycompany.petssystem.repository.TypePetRepository;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author erick
 */
public class UpdatePet extends javax.swing.JInternalFrame {
    
    private final PetRepository petRepository = new PetRepository();
    private final TypePetRepository typePetRepository = new TypePetRepository();

    /**
     * Creates new form UpdatePet
     */
    public UpdatePet() {
        initComponents();
        loadTypes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelUpdateNamePet = new javax.swing.JLabel();
        jLabelUpdateAgePet = new javax.swing.JLabel();
        jLabelUpdateTyPet = new javax.swing.JLabel();
        txtNewNamePet = new javax.swing.JTextField();
        txtNewAgePet = new javax.swing.JTextField();
        jButtonUpdatePet = new javax.swing.JButton();
        txtUpdateID = new javax.swing.JTextField();
        jLabelUpdateId = new javax.swing.JLabel();
        jComboBoxUpdateType = new javax.swing.JComboBox<>();

        setClosable(true);

        jLabelUpdateNamePet.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabelUpdateNamePet.setText("Nuevo nombre");

        jLabelUpdateAgePet.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabelUpdateAgePet.setText("Nueva Edad");

        jLabelUpdateTyPet.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabelUpdateTyPet.setText("Nuevo tipo de mascota");

        txtNewNamePet.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNewNamePet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewNamePetActionPerformed(evt);
            }
        });

        txtNewAgePet.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNewAgePet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewAgePetActionPerformed(evt);
            }
        });

        jButtonUpdatePet.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jButtonUpdatePet.setText("Actualizar Datos");
        jButtonUpdatePet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdatePetActionPerformed(evt);
            }
        });

        txtUpdateID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtUpdateID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpdateIDActionPerformed(evt);
            }
        });

        jLabelUpdateId.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabelUpdateId.setText("ID");

        jComboBoxUpdateType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxUpdateType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxUpdateTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(98, 98, 98)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelUpdateNamePet)
                                            .addComponent(jLabelUpdateAgePet)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabelUpdateTyPet)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabelUpdateId, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNewAgePet, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNewNamePet, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxUpdateType, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUpdateID, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jButtonUpdatePet, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUpdateID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUpdateId, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUpdateNamePet)
                    .addComponent(txtNewNamePet, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUpdateAgePet)
                    .addComponent(txtNewAgePet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxUpdateType, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUpdateTyPet))
                .addGap(28, 28, 28)
                .addComponent(jButtonUpdatePet, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNewNamePetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewNamePetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewNamePetActionPerformed

    private void txtNewAgePetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewAgePetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewAgePetActionPerformed

    private void jButtonUpdatePetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdatePetActionPerformed
        
        try {
            int id = Integer.parseInt(txtUpdateID.getText());
            String name = txtNewNamePet.getText();
            short age = Short.parseShort(txtNewAgePet.getText());
            int index = jComboBoxUpdateType.getSelectedIndex();
            TypePet tipo = typePetRepository.getAllTypePets().get(index);
            int typeId = tipo.getTypeId();

            Pet pet = new Pet(id, name, age, (byte) 1, typeId);
            boolean updatePet = petRepository.updatePet(pet);

            if (updatePet) {
                JOptionPane.showMessageDialog(null, "Mascota actualizada.");
                txtUpdateID.setText("");
                txtNewNamePet.setText("");
                txtNewAgePet.setText("");
                jComboBoxUpdateType.setSelectedIndex(0);
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo actualizar.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "ID, edad y tipo deben ser números ");
        }
    }//GEN-LAST:event_jButtonUpdatePetActionPerformed

    private void txtUpdateIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpdateIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUpdateIDActionPerformed

    private void jComboBoxUpdateTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxUpdateTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxUpdateTypeActionPerformed
    private void loadTypes(){
        jComboBoxUpdateType.removeAllItems();
        try {
            List<TypePet> types = typePetRepository.getAllTypePets();
            
            for (TypePet t:types){
                jComboBoxUpdateType.addItem(t.getDescription());
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error: " + e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonUpdatePet;
    private javax.swing.JComboBox<String> jComboBoxUpdateType;
    private javax.swing.JLabel jLabelUpdateAgePet;
    private javax.swing.JLabel jLabelUpdateId;
    private javax.swing.JLabel jLabelUpdateNamePet;
    private javax.swing.JLabel jLabelUpdateTyPet;
    private javax.swing.JTextField txtNewAgePet;
    private javax.swing.JTextField txtNewNamePet;
    private javax.swing.JTextField txtUpdateID;
    // End of variables declaration//GEN-END:variables
}
