/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.petssystem.gui;

import com.mycompany.petssystem.entities.Pet;
import com.mycompany.petssystem.repository.PetRepository;
import javax.swing.JOptionPane;

/**
 *
 * @author erick
 */
public class UpdatePet extends javax.swing.JInternalFrame {
    
    private final PetRepository petRepository = new PetRepository();

    /**
     * Creates new form UpdatePet
     */
    public UpdatePet() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelUpdateNamePet = new javax.swing.JLabel();
        jLabelUpdateAgePet = new javax.swing.JLabel();
        jLabelUpdateTyPet = new javax.swing.JLabel();
        txtNewNamePet = new javax.swing.JTextField();
        txtNewAgePet = new javax.swing.JTextField();
        txtNewTyPet = new javax.swing.JTextField();
        jButtonUpdatePet = new javax.swing.JButton();
        txtUpdateID = new javax.swing.JTextField();
        jLabelUpdateId = new javax.swing.JLabel();

        setClosable(true);

        jLabelUpdateNamePet.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabelUpdateNamePet.setText("Nuevo nombre");

        jLabelUpdateAgePet.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabelUpdateAgePet.setText("Nueva Edad");

        jLabelUpdateTyPet.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabelUpdateTyPet.setText("Nuevo tipo de mascota");

        txtNewNamePet.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNewNamePet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewNamePetActionPerformed(evt);
            }
        });

        txtNewAgePet.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNewAgePet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewAgePetActionPerformed(evt);
            }
        });

        txtNewTyPet.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNewTyPet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewTyPetActionPerformed(evt);
            }
        });

        jButtonUpdatePet.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jButtonUpdatePet.setText("Actualizar Datos");
        jButtonUpdatePet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdatePetActionPerformed(evt);
            }
        });

        txtUpdateID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtUpdateID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpdateIDActionPerformed(evt);
            }
        });

        jLabelUpdateId.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabelUpdateId.setText("ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addComponent(jButtonUpdatePet, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelUpdateNamePet)
                                    .addComponent(jLabelUpdateAgePet)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addComponent(jLabelUpdateTyPet)))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNewTyPet, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNewAgePet, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                .addComponent(txtNewNamePet)))))
                .addContainerGap(245, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelUpdateId, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtUpdateID, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(249, 249, 249))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUpdateID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUpdateId, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNewNamePet, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUpdateNamePet))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNewAgePet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUpdateAgePet))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUpdateTyPet)
                    .addComponent(txtNewTyPet, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jButtonUpdatePet, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNewNamePetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewNamePetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewNamePetActionPerformed

    private void txtNewAgePetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewAgePetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewAgePetActionPerformed

    private void txtNewTyPetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewTyPetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewTyPetActionPerformed

    private void jButtonUpdatePetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdatePetActionPerformed
        
        try {
            int id = Integer.parseInt(txtUpdateID.getText());
            String name = txtNewNamePet.getText();
            short age = Short.parseShort(txtNewAgePet.getText());
            int typeId = Integer.parseInt(txtNewTyPet.getText());

            Pet pet = new Pet(id, name, age, (byte) 1, typeId);
            boolean updatePet = petRepository.updatePet(pet);

            if (updatePet) {
                JOptionPane.showMessageDialog(null, "Mascota actualizada.");
                txtUpdateID.setText("");
                txtNewNamePet.setText("");
                txtNewAgePet.setText("");
                txtNewTyPet.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo actualizar.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "ID, edad y tipo deben ser números ");
        }
    }//GEN-LAST:event_jButtonUpdatePetActionPerformed

    private void txtUpdateIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpdateIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUpdateIDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonUpdatePet;
    private javax.swing.JLabel jLabelUpdateAgePet;
    private javax.swing.JLabel jLabelUpdateId;
    private javax.swing.JLabel jLabelUpdateNamePet;
    private javax.swing.JLabel jLabelUpdateTyPet;
    private javax.swing.JTextField txtNewAgePet;
    private javax.swing.JTextField txtNewNamePet;
    private javax.swing.JTextField txtNewTyPet;
    private javax.swing.JTextField txtUpdateID;
    // End of variables declaration//GEN-END:variables
}
